### ISSUE TITLE
[Enhancement Request] use a connection pool instead of creating a new connection in the onlineDDL.executor.

### ISSUE THREAD

**Issue by gerayking** [wesql/wescale#281]
# Proposal

Inheriting from Vitess, our onlineddl section contains numerous instances where new connections are established rather than retrieving them from a connection pool. It would be prudent to streamline this portion of the code, ensuring that all connections are sourced from the connection pool. The benefits of this optimization through connection pooling include:

**Regulated Connection Count**: This ensures a consistent number of connections, preventing a surge in DDL operations from causing an excessive number of connections, which might deplete MySQL's memory.

**Performance Enhancement**: Leveraging existing connections eliminates the overhead of initiating new ones, subsequently boosting performance.

**Simplified Code Maintenance**: Consolidating connection management makes the codebase more intuitive and easier to maintain.

**Comment by earayu** [comment]
duplicate issue
