### ISSUE TITLE
[Enhancement Request] Add Existence Verification for Tables in OnlineDDL Drop Statements

### ISSUE THREAD

**Issue by earayu** [wesql/wescale#285]
# Background
Currently, when OnlineDDL is enabled, users are able to successfully submit a drop statement for a table that does not exist. This behavior poses a potential issue and should be addressed.

# Proposal
Our proposal is to implement table existence verification within the drop statement process. This can be achieved by incorporating the verification logic in VTGate. By doing so, we can prevent the execution of drop statements for tables that do not exist, ensuring the integrity of the database.

# Expected Behaviour
```
mysql> show tables from m1;
+--------------+
| Tables_in_m1 |
+--------------+
| t1           |
| t2           |
+--------------+
2 rows in set (0.00 sec)

mysql> drop table t3;
ERROR 1051 (42S02): Unknown table 'm1.t3'
mysql>
mysql>
mysql> drop table if exists t3;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> drop table t2;
Query OK, 0 rows affected (0.00 sec)

mysql> drop table if exists t2;
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> drop table if exists t1;
Query OK, 0 rows affected (0.01 sec)
```

**Comment by newborn22** [comment]
There is another bug related to this one: altering a non-existent table will block all subsequent online-ddl tasks.

As shown in the figure below, altering a table that does not exist will cause all subsequent ddl tasks to be blocked.

You can see that there are only` test_table` and `test_table2` tables in the current database and `test_table3` does not exist, but you can perform alter operations on it.


![image](https://github.com/wesql/wescale/assets/57584044/403a6d6d-2030-4e32-b985-90fa31cf81ca)

You can see that alter `test_table3` is queued.


![image](https://github.com/wesql/wescale/assets/57584044/45e692b0-95d8-4dfe-9444-99722988ab8b)

Then alter `test_table2`, you can see that this ddl is also queued.


![image](https://github.com/wesql/wescale/assets/57584044/a4c12a6f-55a2-46b0-ab8a-59bf45f730a9)
![image](https://github.com/wesql/wescale/assets/57584044/ab28914a-636b-49da-9711-07c5f7bfe19b)
