### ISSUE TITLE
[Enhancement Request] Displaying the execution node type for each SQL statement. 

### ISSUE THREAD

**Issue by newborn22** [wesql/wescale#363]
# Background

vttablet nodes have three types: primary, read-only, and replica. 

Depending on different read-write separation strategies, SQL statements will be routed to different types of nodes for execution. However, current users cannot see on the client side which type of node a specific SQL statement is executed on. 

# Proposal

Adding a dynamic switch, when enabled, the client side will display the execution node type for the current SQL statement.

**Comment by earayu** [comment]
It seems like an interesting issue.
