### ISSUE TITLE
[Enhancement Request] Branch: Support more transform functions

### ISSUE THREAD

**Issue by gerayking** [wesql/wescale#388]
# Proposal

We need more transformation functions sourced from gofakeit.

**Comment by earayu** [comment]
What built-in transform functions do we need to provide?
Let me share my viewpoint:

gofakeit offers a Generate(value string) string function capable of generating almost all types of data based on a template. However, the return value is a string.
This function is quite useful for generating data with business semantics, such as:
Generate("{firstname}")
Generate("{username}")
Generate("{address}")
Generate("{dice:6,[1,2,3,4,5,6]}")

But for other database types (int, float, double, decimal, ...), Generate cannot produce the corresponding types.

Moreover, gofakeit is essentially a Golang open-source library, and the data types it generates are Golang types.
Users fundamentally do not care what the Golang types are, nor do they want to worry about how to convert Golang types into SQL types.

What users care about is: their SQL type is DECIMAL (for example), and WeScale can help them generate fake data of DECIMAL type.

Therefore, providing users with such functionality may be more intuitive:
```sql
SELECT 
    gofakeit("firstname"),
    gofakeit("username"),
    gofakeit("address"),
    gofakeit("{dice:6,[1,2,3,4,5,6]}"),

    gofakeit_bytype("INT"),
    gofakeit_bytype("FLOAT32"),
    gofakeit_bytype("TIMESTAMP"),
    gofakeit_bytype("DECIMAL", "10", "2")
    ...
;
```

**Comment by earayu** [comment]
fixed
