### ISSUE TITLE
[Enhancement Request] Replace the 'throwArgError' with the new error processing method.

### ISSUE THREAD

**Issue by gerayking** [wesql/wescale#393]
# Background

Currently, the original 'evalengine' is exclusively utilized by 'vtgate', allowing 'throwArgError' to be caught by 'vtgate'. However, with the introduction of the branch function in 'vttablet', any argument errors could potentially cause 'vttablet' to fail. Therefore, it is necessary to replace 'throwArgError' with an alternative error processing method in the fake function.

**Comment by earayu** [comment]
fixed
