### ISSUE TITLE
[Documentation Request] Add Tutorial and Blog for WeScale Branching

### ISSUE THREAD

**Issue by earayu** [wesql/wescale#411]
# Proposal
Create a comprehensive tutorial that guides users through the process of using WeScale's branching feature. The tutorial should cover topics such as creating branches, merging branches, and best practices for branching workflows.
Additionally, publish a blog post that highlights the benefits of using WeScale's branching feature and provides real-world examples of how it can improve code collaboration and version control in a team setting. 
By providing these resources, users will have a clear understanding of how to leverage the branching feature in WeScale and be able to adopt effective branching strategies for their projects.

**Comment by gerayking** [comment]
fix #426
