### ISSUE TITLE
[Feature Request] Support collecting all used tables in a SQL

### ISSUE THREAD

**Issue by earayu** [wesql/wescale#457]
To enhance our database system, we should introduce a feature that allows users to collect all the tables referenced within a SQL statement.

**Comment by BruceAko** [comment]
@earayu Could you please elaborate on the task in more detail? I'd like to try it as my first task in `wescale`, thanks :)

**Comment by earayu** [comment]
@BruceAko Hi there,

I apologize for any confusion caused. The issue you mentioned has been resolved, but it appears it wasn't closed properly. Thank you for bringing this to our attention!

We appreciate your involvement and your help in keeping our project's issue tracker up-to-date. If there's anything else related to this issue that needs discussion or you have further questions, please feel free to let us know. Otherwise, I will close this issue now to reflect its resolved status.

Thanks again for your contribution!
