### ISSUE TITLE
[Documentation Request] Deployment Configuration

### ISSUE THREAD

**Issue by solomonope** [wesql/wescale#466]
# Background

I can't seem to find clear documentation on how to deploy Wescale.

I would like to deploy Wescale in Kubernetes cluster, I can't  seem to find documentation on the configuration options for all the component of Wescale

**Comment by earayu** [comment]
Hi, @solomonope 

Thank you for your Documentation Request. This week, I will be adding some articles about how to deploy WeScale in a Kubernetes environment. 

In the meantime, If you want to deploy WeScale in a Kubernetes cluster, you can use KubeBlocks. You can find the documentation for KubeBlocks here: [KubeBlocks Documentation](https://kubeblocks.io/docs/preview/user_docs/try-out-on-playground/try-kubeblocks-on-your-laptop)
And you can find instructions on how to deploy WeScale using KubeBlocks at this link: [Deploying WeScale with KubeBlocks](https://kubeblocks.io/docs/preview/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy#create-a-proxy-cluster)

**Comment by earayu** [comment]
If you would like to deploy wescale in k8s, you can follow this document: https://github.com/wesql/wescale/blob/main/doc%2Ftoturial%2F11-Getting-Started-with-Kubernetes.md
