### ISSUE TITLE
[Feature Request] Add allow list to wescale filter

### ISSUE THREAD

**Issue by newborn22** [wesql/wescale#503]
# Background

When a user deploys a Wescale filter, SQL that matches the corresponding pattern will execute the relevant operation. 

However, some SQL statements may wish to bypass this rule. For example, a user might deploy a wasm plugin filter for all insert SQL statements. Thus, when the user deploys a new wasm plugin, the SQL statement that inserts the wasm binary into the Wescale system table will be affected, which perhaps is not what the user expects.

So maybe we need an allow list function.
# Proposal

There maybe two ways to do this thing:
1.Add a system table for user to config allow list rules: the sql match corresponding pattern will pass relevant filters.
2.Add allow list rule for each filter.

**Comment by ccoVeille** [comment]
If I may, whitelist -> allow list

**Comment by newborn22** [comment]
> If I may, whitelist -> allow list

yeah, it's a better a name!
