### ISSUE TITLE
[Enhancement Request] "show slave status" should upgrade to "show replica status"

### ISSUE THREAD

**Issue by newborn22** [wesql/wescale#545]
# Background

From MySQL 8.0.22, [SHOW SLAVE STATUS](https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html) is deprecated, and from MYSQL 8.4, it will cause an syntax error `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'slave status' at line 1`.

# Proposal

When Wescale is deployed in local, it still relies on 'SLAVE' syntax. We should check the MYSQL version.

**Comment by earayu** [comment]
fixed
