### ISSUE TITLE
Merge the QueryEngine connection pools of vttablet into taskPool

### ISSUE THREAD

**Issue by jairuigou** [wesql/wescale#584]
# Background

This issue is a sub-issue of #563 
# Proposal

Replace the connection pool in QueryEngine with taskPool:
ConnPool, StreamConnPool, ConnWithoutDBPool, StreamWithoutDBConnPool

**Comment by jairuigou** [comment]
I have a question about the use of connection pools in QueryEngine. There are for connection pools in total: `ConnPool, StreamConnPool, ConnWithoutDBPool, StreamWithoutDBConnPool`. The `PoolSizeController` adjust the size of `ConnPool` based on the tx connection pool size and some configurations. However, why don't the other three pools require the similar adjustment?
And is it necessary to keep the ability to adjust the `ConnPool` size independently? If it were merged into `taskPool`, we would only be able to adjust the size of the entire `taskPool`
@earayu

**Comment by earayu** [comment]
You should not replace the connection pool for QueryEngine and TxEngine. 

`TaskPool` is for background tasks like `healthStreamer`, `pool_size_controller`, `onlineDDL`, `tableGC`... etc.

**Comment by earayu** [comment]
QueryEngine is used for processing simple READ requests, TxEngine is used for DML or Transactional/Stateful requests.
