### ISSUE TITLE
[Feature Request] VTDirect: allow VTGate to directly send queries to mysql

### ISSUE THREAD

**Issue by zn9f** [wesql/wescale#592]
Is there a plan to support vtdirect features?

# Background
https://github.com/vitessio/vitess/issues/5791

VTDirect:

The excessive use of CPU due to gRPC continues to be a concern among some adopters. Additionally, Vitess is now being deployed against externally managed databases like RDS and CloudSQL. Such users are reluctant to pay the latency cost of the extra hop.

VTDirect is the ability for VTGate to directly send queries to the mysql instances.

This feature adds the following requirements over the previous ones:

Some features of TabletServer (like sequences) should be disabled or redirected to an actual vttablet.
TabletServers can have a life-cycle as tablets are added and removed from the topo. The variables and end-points need to reflect these changes.
In previous discussions, alternate approaches that did not require a TabletServer refactor were suggested. Given that the TabletServer refactor brings us much closer to this feature, we’ll need to re-evaluate our options for the best approach. This will be a separate RFC.

**Comment by earayu** [comment]
WeScale currently has no plans to support VTDirect. However, I am planning to support running VTTablet and VTGate in the same process with direct communication, eliminating the gRPC layer. The timeline for this feature is not yet determined.

I understand your two main concerns:
1. The gRPC communication between VTGate and VTTablet consuming excessive CPU
2. The additional network RT when VTTablet can't be deployed as a sidecar with external databases, leading to a potentially longer data path: Application->VTGate->VTTablet->MySQL

Merging VTTablet and VTGate into a single process will address both issues while preserving all current functionalities:
- Server-side connection pooling
- MySQL role probing
- Read-write splitting
- Read-after-write consistency
- Online DDL
- WASM plugins
- And more

For current WeScale users, the recommended deployment pattern is to run VTTablet as a sidecar alongside MySQL.
